apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhis-mosip-middleware 
  name: dhis-mosip-middleware-service-prod 
  namespace: dhis-mosip
spec:
  type: ClusterIP
  ports:
  - port: 3000  
    name: http
    targetPort: 3000  
    protocol: TCP
  selector:
    revision: prod_v1.0  
    app: dhis-mosip-middleware 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dhis-mosip-middleware-account 
  namespace: dhis-mosip
  labels:
    app: dhis-mosip-middleware 
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dhis-mosip-middleware 
  name: dhis-mosip-middleware-deployment-prod 
  namespace: dhis-mosip
spec:
  replicas: 1  
  selector:
    matchLabels:
      revision: prod_v1.0  
      app: dhis-mosip-middleware 
  template:
    metadata:
      labels:
        revision: prod_v1.0  
        app: dhis-mosip-middleware 
    spec:
      serviceAccountName: dhis-mosip-middleware-account  
      containers:  
      - image: 160168652050.dkr.ecr.us-west-1.amazonaws.com/dhis2-mosip-middleware:latest
        name: dhis-mosip-middleware-container  
        ports:
        - containerPort: 3000 
        resources:
          requests:
            cpu: "100m"
            memory: 300Mi
          limits:
            memory: 1Gi
        
        envFrom:
        - secretRef:
            name: dhis-mosip-middleware-secret-prod
        imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dhis-mosip-middleware-ingress
  namespace: dhis-mosip
  labels:
    app: dhis-mosip-middleware 
spec:
  ingressClassName: nginx
  tls: 
    - hosts:
        - middleware.mosipcmuafrica.me
      secretName: mosip-tls-cert
  rules:
  - host: middleware.mosipcmuafrica.me 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dhis-mosip-middleware-secret-prod
            port:
              number: 3000
---
kind: Secret
apiVersion: v1
metadata:
  name: dhis-mosip-middleware-secret-prod
  namespace: dhis-mosip
  labels:
    app: dhis-mosip-middleware 
stringData:
  PORT: "3000"
  MOSIP_BASE_ROUTE: "mosip_base_route"
  HOST_NAME: "host_name"
  API_ROUTE: "api_route_to_open"
  ALGORITHM: "algorithm"
  KEY: "key"
  IV: "iv"
  NEXT_PUBLIC_MDS_BYPASS: "bypass"
  MOSIP_BYPASS: "bypass"

type: Opaque
