import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import test from './components/test'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <form onsubmit="validateFormWithJS()">
        <label for="rollNumber">Roll Number:</label>
        <input type="text" name="rollNumber" id="rollNumber" />

        <label for="name">Name:</label>
        <input type="text" name="name" id="name" />

        <button type="submit">Submit</button>
    </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
